// <auto-generated />
using System;
using DbStorageContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbStorageContext.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20230731121154_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfProduction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Depth")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<int>("PalletId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("Boxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfProduction = new DateOnly(2021, 3, 24),
                            Depth = 181.34128153535667557240736764m,
                            Height = 240.57074500938730770782863679m,
                            PalletId = 2,
                            Weight = 21.71951123854576m,
                            Width = 17.231275473921307408574813408m
                        },
                        new
                        {
                            Id = 2,
                            Depth = 103.610664257584474177316658m,
                            ExpiryDate = new DateOnly(2022, 6, 2),
                            Height = 91.16492404430009400852163609m,
                            PalletId = 6,
                            Weight = 23.135048520643632m,
                            Width = 99.44406030259055903270846196m
                        },
                        new
                        {
                            Id = 3,
                            DateOfProduction = new DateOnly(2021, 12, 10),
                            Depth = 207.47001298042166947145021750m,
                            Height = 64.648812990161437948830667390m,
                            PalletId = 5,
                            Weight = 14.190824021514752m,
                            Width = 35.522187771186422613268247296m
                        },
                        new
                        {
                            Id = 4,
                            Depth = 47.966146296593170797428226276m,
                            ExpiryDate = new DateOnly(2022, 6, 23),
                            Height = 152.94972225638981152609076984m,
                            PalletId = 8,
                            Weight = 2.5485321124437534m,
                            Width = 175.17351140823689556517843221m
                        },
                        new
                        {
                            Id = 5,
                            DateOfProduction = new DateOnly(2020, 12, 24),
                            Depth = 59.792537382159934280458248272m,
                            Height = 132.19249274406126053294373387m,
                            PalletId = 1,
                            Weight = 9.443836773836706m,
                            Width = 3.8407218977510767981697448130m
                        },
                        new
                        {
                            Id = 6,
                            Depth = 42.44765398450773207949019173m,
                            ExpiryDate = new DateOnly(2020, 11, 30),
                            Height = 217.48621479965181406859454228m,
                            PalletId = 4,
                            Weight = 23.770051796855298m,
                            Width = 32.701305095891767214893891193m
                        },
                        new
                        {
                            Id = 7,
                            DateOfProduction = new DateOnly(2021, 3, 3),
                            Depth = 89.17877233533332498654402204m,
                            Height = 81.95813492229180082114333341m,
                            PalletId = 7,
                            Weight = 23.574693872709226m,
                            Width = 111.04662141894756011768833307m
                        },
                        new
                        {
                            Id = 8,
                            Depth = 47.69436043217744258640619406m,
                            ExpiryDate = new DateOnly(2020, 12, 22),
                            Height = 139.09859444664398075526692978m,
                            PalletId = 6,
                            Weight = 29.474631628399553m,
                            Width = 108.68559513344956865858008206m
                        },
                        new
                        {
                            Id = 9,
                            DateOfProduction = new DateOnly(2021, 8, 16),
                            Depth = 177.41590952122092811778702728m,
                            Height = 66.773437106956969577971998184m,
                            PalletId = 5,
                            Weight = 10.419445076821868m,
                            Width = 11.639366847420133179583477536m
                        },
                        new
                        {
                            Id = 10,
                            Depth = 65.617756333822800640262572168m,
                            ExpiryDate = new DateOnly(2021, 11, 28),
                            Height = 162.96967863652731207991176184m,
                            PalletId = 1,
                            Weight = 16.625839773790046m,
                            Width = 25.615404193761383334060109836m
                        },
                        new
                        {
                            Id = 11,
                            DateOfProduction = new DateOnly(2022, 3, 21),
                            Depth = 26.352708489220838318616399118m,
                            Height = 284.09117859099425769094773450m,
                            PalletId = 3,
                            Weight = 13.802430249854086m,
                            Width = 43.855931325986190001209807348m
                        },
                        new
                        {
                            Id = 12,
                            Depth = 49.675264615403299294694477802m,
                            ExpiryDate = new DateOnly(2021, 10, 10),
                            Height = 176.55576502181494937925048259m,
                            PalletId = 9,
                            Weight = 9.386568980976794m,
                            Width = 64.210262963662571728355824033m
                        },
                        new
                        {
                            Id = 13,
                            DateOfProduction = new DateOnly(2021, 3, 31),
                            Depth = 78.166682715773280284832320016m,
                            Height = 95.56672419190715475321981674m,
                            PalletId = 1,
                            Weight = 25.859989135566474m,
                            Width = 16.173587206736936264664980880m
                        },
                        new
                        {
                            Id = 14,
                            Depth = 32.383931520492236835170645092m,
                            ExpiryDate = new DateOnly(2020, 12, 8),
                            Height = 215.75162186866466517327836902m,
                            PalletId = 9,
                            Weight = 13.479597196993266m,
                            Width = 19.343687553120254813923817278m
                        },
                        new
                        {
                            Id = 15,
                            DateOfProduction = new DateOnly(2021, 10, 31),
                            Depth = 101.63687830537417771092983739m,
                            Height = 157.11061673178005989977873103m,
                            PalletId = 6,
                            Weight = 7.043259713672967m,
                            Width = 50.321488925755124400723269224m
                        },
                        new
                        {
                            Id = 16,
                            Depth = 208.04562483963443168622875102m,
                            ExpiryDate = new DateOnly(2021, 12, 16),
                            Height = 78.675312828747510913911904378m,
                            PalletId = 5,
                            Weight = 7.351626507022006m,
                            Width = 11.791498120776324276500692520m
                        },
                        new
                        {
                            Id = 17,
                            DateOfProduction = new DateOnly(2021, 1, 15),
                            Depth = 25.820909938609490902090277733m,
                            Height = 24.009067032572650601224052389m,
                            PalletId = 8,
                            Weight = 11.830977635200271m,
                            Width = 46.041090999186011280571513612m
                        },
                        new
                        {
                            Id = 18,
                            Depth = 36.047848532607979443415114033m,
                            ExpiryDate = new DateOnly(2020, 11, 1),
                            Height = 12.389990262045240015901210091m,
                            PalletId = 4,
                            Weight = 17.947324731120981m,
                            Width = 72.127019293201807309586867811m
                        },
                        new
                        {
                            Id = 19,
                            DateOfProduction = new DateOnly(2021, 9, 5),
                            Depth = 76.11123963216072200841519996m,
                            Height = 16.227392715695253958269458201m,
                            PalletId = 2,
                            Weight = 3.6113275132190362m,
                            Width = 15.849879417608544851463483971m
                        },
                        new
                        {
                            Id = 20,
                            Depth = 101.32933191869997658693211814m,
                            ExpiryDate = new DateOnly(2021, 9, 14),
                            Height = 118.69487073652884618252683949m,
                            PalletId = 1,
                            Weight = 2.4902831150615298m,
                            Width = 11.388454463768826407425038937m
                        },
                        new
                        {
                            Id = 21,
                            DateOfProduction = new DateOnly(2022, 1, 18),
                            Depth = 33.280097452437440922706531438m,
                            Height = 233.99409391086719022957049306m,
                            PalletId = 9,
                            Weight = 2.6882480546245343m,
                            Width = 40.314111378689515615552940923m
                        },
                        new
                        {
                            Id = 22,
                            Depth = 68.47108054236740841636566524m,
                            ExpiryDate = new DateOnly(2022, 4, 29),
                            Height = 100.04370846703309029718991154m,
                            PalletId = 4,
                            Weight = 29.287853622583724m,
                            Width = 86.85917493291288650374903917m
                        },
                        new
                        {
                            Id = 23,
                            DateOfProduction = new DateOnly(2021, 2, 22),
                            Depth = 2.4282120873538890615997481693m,
                            Height = 173.11086322448290434599333605m,
                            PalletId = 9,
                            Weight = 17.145641091106187m,
                            Width = 72.962870290468033005772872544m
                        },
                        new
                        {
                            Id = 24,
                            Depth = 166.37233728314609591260131048m,
                            ExpiryDate = new DateOnly(2021, 7, 9),
                            Height = 87.4507224649283966746724854m,
                            PalletId = 5,
                            Weight = 16.36271785671813m,
                            Width = 24.24950710887020877692269448m
                        },
                        new
                        {
                            Id = 25,
                            DateOfProduction = new DateOnly(2021, 11, 26),
                            Depth = 107.02930485421291752568931475m,
                            Height = 205.93004555225991050532909096m,
                            PalletId = 7,
                            Weight = 22.138625692502923m,
                            Width = 175.95288619478910808262571483m
                        },
                        new
                        {
                            Id = 26,
                            Depth = 101.63634086119612128011352885m,
                            ExpiryDate = new DateOnly(2021, 2, 7),
                            Height = 94.85274103157769808029760978m,
                            PalletId = 1,
                            Weight = 11.504258584246549m,
                            Width = 15.610026203851667096088458210m
                        },
                        new
                        {
                            Id = 27,
                            DateOfProduction = new DateOnly(2022, 3, 30),
                            Depth = 129.27404095494488850510948174m,
                            Height = 207.0674242024623023991735774m,
                            PalletId = 7,
                            Weight = 26.664625194223694m,
                            Width = 50.661123363244966035421547046m
                        },
                        new
                        {
                            Id = 28,
                            Depth = 69.710154861596061431975776890m,
                            ExpiryDate = new DateOnly(2022, 2, 23),
                            Height = 13.004760626020415979639528383m,
                            PalletId = 8,
                            Weight = 23.474582104375624m,
                            Width = 197.25419399135302898253448514m
                        },
                        new
                        {
                            Id = 29,
                            DateOfProduction = new DateOnly(2022, 5, 31),
                            Depth = 3.3070839989588679521085255458m,
                            Height = 155.21590219565062954579568152m,
                            PalletId = 9,
                            Weight = 29.190766993455035m,
                            Width = 27.047823199868203467248931319m
                        },
                        new
                        {
                            Id = 30,
                            Depth = 42.164075748477532541158237792m,
                            ExpiryDate = new DateOnly(2021, 5, 11),
                            Height = 8.886559595583627027363611527m,
                            PalletId = 3,
                            Weight = 3.1490118103160832m,
                            Width = 58.17393628449706883286648202m
                        },
                        new
                        {
                            Id = 31,
                            DateOfProduction = new DateOnly(2021, 2, 2),
                            Depth = 49.554332898597996500515784543m,
                            Height = 260.63589881367521526121995382m,
                            PalletId = 9,
                            Weight = 1.8099200963150562m,
                            Width = 97.69118299457013368781537750m
                        },
                        new
                        {
                            Id = 32,
                            Depth = 47.810923121940927070047980931m,
                            ExpiryDate = new DateOnly(2021, 12, 1),
                            Height = 225.13196018653770475386785614m,
                            PalletId = 9,
                            Weight = 4.430369033687312m,
                            Width = 45.792099834009959641625921287m
                        },
                        new
                        {
                            Id = 33,
                            DateOfProduction = new DateOnly(2021, 2, 10),
                            Depth = 99.7213845794202784785345517m,
                            Height = 107.72082886499975972869590923m,
                            PalletId = 7,
                            Weight = 15.008511324669997m,
                            Width = 76.690497409842130714988353008m
                        },
                        new
                        {
                            Id = 34,
                            Depth = 194.95298523580733694693936612m,
                            ExpiryDate = new DateOnly(2021, 5, 6),
                            Height = 50.032022041360529822731763602m,
                            PalletId = 5,
                            Weight = 7.96310795376869m,
                            Width = 85.33326209904626118180048901m
                        },
                        new
                        {
                            Id = 35,
                            DateOfProduction = new DateOnly(2021, 11, 3),
                            Depth = 105.78102724197601318114581318m,
                            Height = 63.821661243010498072434063508m,
                            PalletId = 5,
                            Weight = 9.831973803303646m,
                            Width = 76.605178513929959174189265792m
                        },
                        new
                        {
                            Id = 36,
                            Depth = 36.337076607186683579871995101m,
                            ExpiryDate = new DateOnly(2022, 1, 2),
                            Height = 169.58174135299380717885101137m,
                            PalletId = 9,
                            Weight = 8.07645546083052m,
                            Width = 63.011171795619842958303126784m
                        },
                        new
                        {
                            Id = 37,
                            DateOfProduction = new DateOnly(2021, 11, 4),
                            Depth = 66.370063517971439130113877188m,
                            Height = 74.927582834325573497014709909m,
                            PalletId = 7,
                            Weight = 25.786254083401348m,
                            Width = 82.00049941956366429266567328m
                        },
                        new
                        {
                            Id = 38,
                            Depth = 11.634882676063880939118896856m,
                            ExpiryDate = new DateOnly(2021, 6, 20),
                            Height = 16.267352585416731795160134673m,
                            PalletId = 6,
                            Weight = 12.874246566613871m,
                            Width = 141.13242575084291620215466298m
                        },
                        new
                        {
                            Id = 39,
                            DateOfProduction = new DateOnly(2021, 4, 4),
                            Depth = 74.586180699701392391751177934m,
                            Height = 160.88555528734554777176477425m,
                            PalletId = 4,
                            Weight = 5.319955421341714m,
                            Width = 85.44879799837261039489261491m
                        },
                        new
                        {
                            Id = 40,
                            Depth = 89.34485730248142896302614773m,
                            ExpiryDate = new DateOnly(2021, 11, 23),
                            Height = 56.809549223150646271887203344m,
                            PalletId = 1,
                            Weight = 1.8766967454647595m,
                            Width = 25.672342144118248057794156175m
                        },
                        new
                        {
                            Id = 41,
                            DateOfProduction = new DateOnly(2022, 3, 27),
                            Depth = 46.54777479490908409262262168m,
                            Height = 61.575971173624448601095371060m,
                            PalletId = 6,
                            Weight = 19.644629127408271m,
                            Width = 130.00105652720525627117205651m
                        },
                        new
                        {
                            Id = 42,
                            Depth = 111.23755382625396147583332984m,
                            ExpiryDate = new DateOnly(2021, 6, 4),
                            Height = 108.89698315545244799065213912m,
                            PalletId = 7,
                            Weight = 27.354480168981518m,
                            Width = 203.31832462322889980752548353m
                        },
                        new
                        {
                            Id = 43,
                            DateOfProduction = new DateOnly(2021, 10, 8),
                            Depth = 46.981868258545314971549357728m,
                            Height = 5.081514085461858753679465555m,
                            PalletId = 9,
                            Weight = 23.166382782401034m,
                            Width = 5.1439046383206617926079831563m
                        },
                        new
                        {
                            Id = 44,
                            Depth = 24.642790102017907601788474234m,
                            ExpiryDate = new DateOnly(2022, 6, 4),
                            Height = 231.7959191724886253048518303m,
                            PalletId = 3,
                            Weight = 22.222666377950149m,
                            Width = 48.656876847243443059026924114m
                        },
                        new
                        {
                            Id = 45,
                            DateOfProduction = new DateOnly(2021, 9, 10),
                            Depth = 18.806178822222387818803115921m,
                            Height = 27.249693772259347070302397314m,
                            PalletId = 8,
                            Weight = 29.970936734420004m,
                            Width = 152.80010325735432121713069398m
                        },
                        new
                        {
                            Id = 46,
                            Depth = 97.38016852854670030065248702m,
                            ExpiryDate = new DateOnly(2020, 10, 2),
                            Height = 70.08343440897646443820685386m,
                            PalletId = 1,
                            Weight = 12.045739479174107m,
                            Width = 23.071644147021514192637156314m
                        },
                        new
                        {
                            Id = 47,
                            DateOfProduction = new DateOnly(2021, 5, 20),
                            Depth = 43.092779213350010392667782311m,
                            Height = 18.958383361872532203518294365m,
                            PalletId = 8,
                            Weight = 18.232292134951025m,
                            Width = 234.95615816492149472327572740m
                        },
                        new
                        {
                            Id = 48,
                            Depth = 112.68473328102014520537148818m,
                            ExpiryDate = new DateOnly(2022, 4, 19),
                            Height = 57.255241214067474581432158336m,
                            PalletId = 5,
                            Weight = 11.036065603404487m,
                            Width = 26.425547699604540184010491928m
                        },
                        new
                        {
                            Id = 49,
                            DateOfProduction = new DateOnly(2021, 1, 9),
                            Depth = 35.94405102338634771771198858m,
                            Height = 158.47909920176844757740666708m,
                            PalletId = 6,
                            Weight = 10.795691118588103m,
                            Width = 82.51899852471631032479140145m
                        },
                        new
                        {
                            Id = 50,
                            Depth = 156.13271722932376728971692540m,
                            ExpiryDate = new DateOnly(2021, 11, 14),
                            Height = 189.75015780309177061786212925m,
                            PalletId = 2,
                            Weight = 11.110531712694517m,
                            Width = 4.7661532872176193467238637600m
                        });
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Depth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Depth = 133.141520683688m,
                            Height = 26.1517678001185m,
                            Width = 192.765850379962m
                        },
                        new
                        {
                            Id = 2,
                            Depth = 236.32781821884m,
                            Height = 25.6023881492576m,
                            Width = 257.453619143826m
                        },
                        new
                        {
                            Id = 3,
                            Depth = 57.037847578729m,
                            Height = 135.994854891218m,
                            Width = 295.374079750009m
                        },
                        new
                        {
                            Id = 4,
                            Depth = 111.923778192009m,
                            Height = 94.1080346272008m,
                            Width = 262.037973434761m
                        },
                        new
                        {
                            Id = 5,
                            Depth = 209.94116221914m,
                            Height = 104.211238491624m,
                            Width = 104.607466385818m
                        },
                        new
                        {
                            Id = 6,
                            Depth = 141.82395733659m,
                            Height = 177.350900741942m,
                            Width = 189.609354226645m
                        },
                        new
                        {
                            Id = 7,
                            Depth = 138.062942292987m,
                            Height = 256.451186371418m,
                            Width = 221.078226430589m
                        },
                        new
                        {
                            Id = 8,
                            Depth = 74.0326760460022m,
                            Height = 250.055445868852m,
                            Width = 193.304702669959m
                        },
                        new
                        {
                            Id = 9,
                            Depth = 58.9465469143748m,
                            Height = 132.071155990003m,
                            Width = 285.10769725711m
                        });
                });

            modelBuilder.Entity("Box", b =>
                {
                    b.HasOne("Pallet", "Pallet")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
