// <auto-generated />
using FileStorageContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileStorageContext.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230725090704_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Depth")
                        .HasPrecision(8, 3)
                        .HasColumnType("NUMERIC(8,3)");

                    b.Property<decimal>("Height")
                        .HasPrecision(8, 3)
                        .HasColumnType("NUMERIC(8,3)");

                    b.Property<int>("PalletId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasPrecision(8, 3)
                        .HasColumnType("NUMERIC(8,3)");

                    b.Property<decimal>("Width")
                        .HasPrecision(8, 3)
                        .HasColumnType("NUMERIC(8,3)");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("Boxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Depth = 166.430897502964m,
                            Height = 5.91732504520062m,
                            PalletId = 10,
                            Weight = 85.8901913981985m,
                            Width = 75.8627802133085m
                        },
                        new
                        {
                            Id = 2,
                            Depth = 58.8892903480893m,
                            Height = 173.769493594898m,
                            PalletId = 9,
                            Weight = 95.8089998806914m,
                            Width = 12.1658635968969m
                        },
                        new
                        {
                            Id = 3,
                            Depth = 161.922934214724m,
                            Height = 56.7168373103823m,
                            PalletId = 6,
                            Weight = 7.0037391425877m,
                            Width = 165.584964735159m
                        },
                        new
                        {
                            Id = 4,
                            Depth = 125.44125990079m,
                            Height = 41.0094654346143m,
                            PalletId = 9,
                            Weight = 172.282044564533m,
                            Width = 130.526246430794m
                        },
                        new
                        {
                            Id = 5,
                            Depth = 57.0998286719885m,
                            Height = 79.7325883577645m,
                            PalletId = 1,
                            Weight = 87.7716811025322m,
                            Width = 149.605982018021m
                        },
                        new
                        {
                            Id = 6,
                            Depth = 199.603498670317m,
                            Height = 112.917125381123m,
                            PalletId = 10,
                            Weight = 98.379363440691m,
                            Width = 190.901525894673m
                        },
                        new
                        {
                            Id = 7,
                            Depth = 95.378038032443m,
                            Height = 112.474688318648m,
                            PalletId = 8,
                            Weight = 197.844192679046m,
                            Width = 60.4486598633574m
                        },
                        new
                        {
                            Id = 8,
                            Depth = 17.443372422391m,
                            Height = 137.434912230963m,
                            PalletId = 9,
                            Weight = 176.820634994626m,
                            Width = 53.8618662644769m
                        },
                        new
                        {
                            Id = 9,
                            Depth = 106.686712011772m,
                            Height = 155.233851341237m,
                            PalletId = 2,
                            Weight = 87.7846608701882m,
                            Width = 128.301050141038m
                        },
                        new
                        {
                            Id = 10,
                            Depth = 86.4618694185563m,
                            Height = 107.871463780885m,
                            PalletId = 2,
                            Weight = 25.5813720315532m,
                            Width = 144.664566443718m
                        },
                        new
                        {
                            Id = 11,
                            Depth = 48.9922042049292m,
                            Height = 57.083478124559m,
                            PalletId = 5,
                            Weight = 195.257756141242m,
                            Width = 8.15250627691386m
                        },
                        new
                        {
                            Id = 12,
                            Depth = 163.440290503858m,
                            Height = 172.73319319965m,
                            PalletId = 10,
                            Weight = 159.208019108909m,
                            Width = 127.32011539376m
                        },
                        new
                        {
                            Id = 13,
                            Depth = 45.1078793796886m,
                            Height = 160.571446845798m,
                            PalletId = 5,
                            Weight = 152.244593404888m,
                            Width = 162.765622543585m
                        },
                        new
                        {
                            Id = 14,
                            Depth = 61.9988581022327m,
                            Height = 73.6582945237802m,
                            PalletId = 7,
                            Weight = 9.97155475242628m,
                            Width = 114.040847077611m
                        },
                        new
                        {
                            Id = 15,
                            Depth = 98.7675702375655m,
                            Height = 137.67122685493m,
                            PalletId = 6,
                            Weight = 40.6166730339725m,
                            Width = 184.513981831913m
                        },
                        new
                        {
                            Id = 16,
                            Depth = 8.69069179221646m,
                            Height = 52.8186018314104m,
                            PalletId = 5,
                            Weight = 136.715896209518m,
                            Width = 32.5014513096913m
                        },
                        new
                        {
                            Id = 17,
                            Depth = 188.737419441437m,
                            Height = 91.246210085493m,
                            PalletId = 10,
                            Weight = 32.7176072759543m,
                            Width = 133.937681482645m
                        },
                        new
                        {
                            Id = 18,
                            Depth = 92.9108670054124m,
                            Height = 124.747702997976m,
                            PalletId = 10,
                            Weight = 119.743899885217m,
                            Width = 130.092455590292m
                        },
                        new
                        {
                            Id = 19,
                            Depth = 56.460858049107m,
                            Height = 191.111727362979m,
                            PalletId = 8,
                            Weight = 87.0768164545256m,
                            Width = 43.2095483179541m
                        },
                        new
                        {
                            Id = 20,
                            Depth = 51.5731148021222m,
                            Height = 44.6733857083772m,
                            PalletId = 7,
                            Weight = 173.31791020658m,
                            Width = 28.8537670109265m
                        },
                        new
                        {
                            Id = 21,
                            Depth = 84.0460960506281m,
                            Height = 44.4380766687658m,
                            PalletId = 2,
                            Weight = 185.171398332442m,
                            Width = 117.797183538127m
                        },
                        new
                        {
                            Id = 22,
                            Depth = 187.232075417821m,
                            Height = 71.4957161802554m,
                            PalletId = 2,
                            Weight = 99.1316229899558m,
                            Width = 24.1441483301444m
                        },
                        new
                        {
                            Id = 23,
                            Depth = 113.280806831709m,
                            Height = 179.965602981649m,
                            PalletId = 7,
                            Weight = 90.2166972342561m,
                            Width = 189.95159432964m
                        },
                        new
                        {
                            Id = 24,
                            Depth = 115.714950639475m,
                            Height = 197.163357063256m,
                            PalletId = 3,
                            Weight = 105.451179347577m,
                            Width = 180.719732520838m
                        },
                        new
                        {
                            Id = 25,
                            Depth = 90.4256010218682m,
                            Height = 23.7468626723447m,
                            PalletId = 2,
                            Weight = 100.833369623977m,
                            Width = 118.976212092984m
                        },
                        new
                        {
                            Id = 26,
                            Depth = 174.680391337939m,
                            Height = 123.690290541911m,
                            PalletId = 6,
                            Weight = 14.0861463640145m,
                            Width = 5.83487681997927m
                        },
                        new
                        {
                            Id = 27,
                            Depth = 191.78109715581m,
                            Height = 10.5576502858599m,
                            PalletId = 3,
                            Weight = 6.53703009966182m,
                            Width = 13.3119103175726m
                        },
                        new
                        {
                            Id = 28,
                            Depth = 67.0333670038313m,
                            Height = 103.733822212999m,
                            PalletId = 3,
                            Weight = 167.428411393503m,
                            Width = 51.048583935718m
                        },
                        new
                        {
                            Id = 29,
                            Depth = 85.3545953167347m,
                            Height = 187.345253630996m,
                            PalletId = 6,
                            Weight = 69.3903889423054m,
                            Width = 35.7735146103087m
                        },
                        new
                        {
                            Id = 30,
                            Depth = 128.567412536925m,
                            Height = 48.0759669259585m,
                            PalletId = 1,
                            Weight = 167.800241499213m,
                            Width = 113.982806079299m
                        },
                        new
                        {
                            Id = 31,
                            Depth = 109.323807569625m,
                            Height = 171.240836433748m,
                            PalletId = 7,
                            Weight = 133.388869627244m,
                            Width = 4.10382645196288m
                        },
                        new
                        {
                            Id = 32,
                            Depth = 51.2684503565438m,
                            Height = 190.59106612497m,
                            PalletId = 8,
                            Weight = 123.909516917138m,
                            Width = 114.715540932067m
                        },
                        new
                        {
                            Id = 33,
                            Depth = 68.6691421178756m,
                            Height = 120.06640030009m,
                            PalletId = 10,
                            Weight = 4.2890394270749m,
                            Width = 167.46141856551m
                        },
                        new
                        {
                            Id = 34,
                            Depth = 78.7454396320828m,
                            Height = 152.853207386959m,
                            PalletId = 5,
                            Weight = 16.7099336272121m,
                            Width = 195.715085755601m
                        },
                        new
                        {
                            Id = 35,
                            Depth = 32.7145629271943m,
                            Height = 53.4502979775414m,
                            PalletId = 6,
                            Weight = 24.9917680280168m,
                            Width = 170.146491209476m
                        },
                        new
                        {
                            Id = 36,
                            Depth = 72.7335514303575m,
                            Height = 79.1543241046776m,
                            PalletId = 2,
                            Weight = 3.75157308199623m,
                            Width = 61.3508741253846m
                        },
                        new
                        {
                            Id = 37,
                            Depth = 142.637967183871m,
                            Height = 87.9284967668424m,
                            PalletId = 7,
                            Weight = 185.002487922535m,
                            Width = 146.746391312612m
                        },
                        new
                        {
                            Id = 38,
                            Depth = 48.4266781240974m,
                            Height = 16.057705867413m,
                            PalletId = 5,
                            Weight = 90.9709217482664m,
                            Width = 84.479806486945m
                        },
                        new
                        {
                            Id = 39,
                            Depth = 8.57774400840818m,
                            Height = 11.9653551875661m,
                            PalletId = 2,
                            Weight = 109.567266295064m,
                            Width = 60.7371611775401m
                        },
                        new
                        {
                            Id = 40,
                            Depth = 34.4691509124792m,
                            Height = 66.6488139110834m,
                            PalletId = 10,
                            Weight = 60.4033596648346m,
                            Width = 38.8907938337921m
                        },
                        new
                        {
                            Id = 41,
                            Depth = 128.523441109866m,
                            Height = 77.7902743236654m,
                            PalletId = 7,
                            Weight = 58.7988954853358m,
                            Width = 3.26892440339577m
                        },
                        new
                        {
                            Id = 42,
                            Depth = 148.420068509608m,
                            Height = 88.4287494275293m,
                            PalletId = 9,
                            Weight = 90.4416240976837m,
                            Width = 127.059177820142m
                        },
                        new
                        {
                            Id = 43,
                            Depth = 29.4296293894465m,
                            Height = 141.917184117414m,
                            PalletId = 7,
                            Weight = 36.9780792541609m,
                            Width = 54.9774314638174m
                        },
                        new
                        {
                            Id = 44,
                            Depth = 156.332160287848m,
                            Height = 133.002623402921m,
                            PalletId = 4,
                            Weight = 59.4716651573274m,
                            Width = 148.580274763469m
                        },
                        new
                        {
                            Id = 45,
                            Depth = 52.3745075734664m,
                            Height = 134.964410764237m,
                            PalletId = 1,
                            Weight = 187.034044164505m,
                            Width = 195.56991238943m
                        },
                        new
                        {
                            Id = 46,
                            Depth = 12.2261805996077m,
                            Height = 106.195617038928m,
                            PalletId = 2,
                            Weight = 104.987466388856m,
                            Width = 53.9448226632849m
                        },
                        new
                        {
                            Id = 47,
                            Depth = 13.6458586084765m,
                            Height = 73.5787524861449m,
                            PalletId = 4,
                            Weight = 189.260317131407m,
                            Width = 75.0521840497359m
                        },
                        new
                        {
                            Id = 48,
                            Depth = 68.3984108370874m,
                            Height = 116.801637732072m,
                            PalletId = 5,
                            Weight = 19.9967659983462m,
                            Width = 167.162424359317m
                        },
                        new
                        {
                            Id = 49,
                            Depth = 103.752305805466m,
                            Height = 21.8119535281082m,
                            PalletId = 8,
                            Weight = 138.413411278772m,
                            Width = 134.13704201417m
                        },
                        new
                        {
                            Id = 50,
                            Depth = 85.7371831317506m,
                            Height = 47.6784290904429m,
                            PalletId = 2,
                            Weight = 129.919802550635m,
                            Width = 153.428451923817m
                        });
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Depth")
                        .HasPrecision(8, 3)
                        .HasColumnType("NUMERIC(8,3)");

                    b.Property<decimal>("Height")
                        .HasPrecision(8, 3)
                        .HasColumnType("NUMERIC(8,3)");

                    b.Property<decimal>("Width")
                        .HasPrecision(8, 3)
                        .HasColumnType("NUMERIC(8,3)");

                    b.HasKey("Id");

                    b.ToTable("Pallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Depth = 522.303132645606m,
                            Height = 312.52802176689m,
                            Width = 917.705874338783m
                        },
                        new
                        {
                            Id = 2,
                            Depth = 225.714844107561m,
                            Height = 771.108011003377m,
                            Width = 581.790752355735m
                        },
                        new
                        {
                            Id = 3,
                            Depth = 572.91094030983m,
                            Height = 782.602417506904m,
                            Width = 142.142688558135m
                        },
                        new
                        {
                            Id = 4,
                            Depth = 991.730098039494m,
                            Height = 550.909015072857m,
                            Width = 81.615180480991m
                        },
                        new
                        {
                            Id = 5,
                            Depth = 68.1711742248592m,
                            Height = 136.67310137252m,
                            Width = 545.341994467166m
                        },
                        new
                        {
                            Id = 6,
                            Depth = 891.475021078382m,
                            Height = 72.8426054095711m,
                            Width = 998.650455582422m
                        },
                        new
                        {
                            Id = 7,
                            Depth = 984.163513629121m,
                            Height = 522.739077039483m,
                            Width = 151.487117665714m
                        },
                        new
                        {
                            Id = 8,
                            Depth = 514.825126120238m,
                            Height = 293.521086538142m,
                            Width = 281.44633746929m
                        },
                        new
                        {
                            Id = 9,
                            Depth = 553.693954327412m,
                            Height = 273.234295074668m,
                            Width = 853.791080594966m
                        },
                        new
                        {
                            Id = 10,
                            Depth = 716.421334024955m,
                            Height = 207.010210697893m,
                            Width = 274.318625521338m
                        });
                });

            modelBuilder.Entity("Box", b =>
                {
                    b.HasOne("Pallet", "Pallet")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
