// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DbStorageContext.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20230725143129_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DateOfProduction")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Depth")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<int>("PalletId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Weight")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("Boxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfProdaction = new DateOnly(2021, 3, 25),
                            Depth = 211.14774153125669693111249465m,
                            Height = 113.47734842348327051579454223m,
                            PalletId = 7,
                            Weight = 28.145790569931025m,
                            Width = 67.673403894104358267209257294m
                        },
                        new
                        {
                            Id = 2,
                            Depth = 52.377765842763469890549570084m,
                            ExpiryDate = new DateOnly(2022, 3, 18),
                            Height = 12.901976094915814712943860015m,
                            PalletId = 8,
                            Weight = 14.867701634284475m,
                            Width = 127.01356453069658540245131343m
                        },
                        new
                        {
                            Id = 3,
                            DateOfProdaction = new DateOnly(2021, 2, 11),
                            Depth = 156.25520573949368647584723380m,
                            Height = 74.80120096810071685382981843m,
                            PalletId = 3,
                            Weight = 12.911285963314159m,
                            Width = 25.438457669580783507541218540m
                        },
                        new
                        {
                            Id = 4,
                            Depth = 123.71376562485999043549519276m,
                            ExpiryDate = new DateOnly(2021, 6, 29),
                            Height = 50.943245068531253674916259238m,
                            PalletId = 2,
                            Weight = 28.984612803599913m,
                            Width = 18.449994257285123731749612875m
                        },
                        new
                        {
                            Id = 5,
                            DateOfProdaction = new DateOnly(2021, 9, 1),
                            Depth = 254.85234427307747729730147709m,
                            Height = 71.136504754468117365848332940m,
                            PalletId = 6,
                            Weight = 24.596989876755029m,
                            Width = 69.69952057226928768698720272m
                        },
                        new
                        {
                            Id = 6,
                            Depth = 103.21205605430211948600331789m,
                            ExpiryDate = new DateOnly(2021, 8, 25),
                            Height = 25.641872248646284213033864775m,
                            PalletId = 2,
                            Weight = 26.449778578407728m,
                            Width = 75.640454596767904167735426150m
                        },
                        new
                        {
                            Id = 7,
                            DateOfProdaction = new DateOnly(2022, 3, 3),
                            Depth = 51.234251891278561633078469053m,
                            Height = 140.11843308164109169534432074m,
                            PalletId = 9,
                            Weight = 17.448792675671202m,
                            Width = 57.844242303856471729186144774m
                        },
                        new
                        {
                            Id = 8,
                            Depth = 49.860446219368045793131002688m,
                            ExpiryDate = new DateOnly(2022, 1, 12),
                            Height = 111.94719347046429829813328153m,
                            PalletId = 5,
                            Weight = 29.438133722136657m,
                            Width = 11.118995794089143622859219299m
                        },
                        new
                        {
                            Id = 9,
                            DateOfProdaction = new DateOnly(2022, 3, 1),
                            Depth = 5.5458213024897550185948795371m,
                            Height = 127.58729778810003771321215059m,
                            PalletId = 4,
                            Weight = 18.0729313357971m,
                            Width = 17.653955633288674432271591830m
                        },
                        new
                        {
                            Id = 10,
                            Depth = 101.22153802397773863347783662m,
                            ExpiryDate = new DateOnly(2021, 1, 6),
                            Height = 240.59726932446513540100702243m,
                            PalletId = 6,
                            Weight = 4.720321563404351m,
                            Width = 27.432564932870196668530248282m
                        },
                        new
                        {
                            Id = 11,
                            DateOfProdaction = new DateOnly(2020, 11, 19),
                            Depth = 20.428240968380442201358837817m,
                            Height = 207.88552774036654448612086702m,
                            PalletId = 1,
                            Weight = 29.529734284767218m,
                            Width = 219.78468888125413045132062200m
                        },
                        new
                        {
                            Id = 12,
                            Depth = 43.329572086634026204469205349m,
                            ExpiryDate = new DateOnly(2021, 3, 19),
                            Height = 235.81779317965849567771305060m,
                            PalletId = 6,
                            Weight = 5.860225453966047m,
                            Width = 73.321440885000730760334879544m
                        },
                        new
                        {
                            Id = 13,
                            DateOfProdaction = new DateOnly(2021, 10, 29),
                            Depth = 19.132067910988209726735246370m,
                            Height = 33.794824644651700460617731259m,
                            PalletId = 2,
                            Weight = 7.376340298691176m,
                            Width = 93.09030887607131347667363100m
                        },
                        new
                        {
                            Id = 14,
                            Depth = 43.901502448989175570691172442m,
                            ExpiryDate = new DateOnly(2020, 12, 27),
                            Height = 125.36477926367235529989222155m,
                            PalletId = 8,
                            Weight = 4.036209676250666m,
                            Width = 178.57642317268480866243938369m
                        },
                        new
                        {
                            Id = 15,
                            DateOfProdaction = new DateOnly(2021, 3, 17),
                            Depth = 26.494645109652585439910302718m,
                            Height = 130.45343880598368796429343786m,
                            PalletId = 5,
                            Weight = 29.787548951625974m,
                            Width = 68.328814393561205606729030579m
                        },
                        new
                        {
                            Id = 16,
                            Depth = 38.990251629974019757053729535m,
                            ExpiryDate = new DateOnly(2021, 11, 14),
                            Height = 46.933411352694901001746265894m,
                            PalletId = 3,
                            Weight = 7.591446017229963m,
                            Width = 8.571115731381446036124404672m
                        },
                        new
                        {
                            Id = 17,
                            DateOfProdaction = new DateOnly(2022, 7, 20),
                            Depth = 37.801990950706632534085592946m,
                            Height = 57.29266937793252891665571785m,
                            PalletId = 8,
                            Weight = 29.435978292366737m,
                            Width = 148.11740691215637787637893798m
                        },
                        new
                        {
                            Id = 18,
                            Depth = 40.670339541012037957683411583m,
                            ExpiryDate = new DateOnly(2021, 1, 30),
                            Height = 234.99547344129430268881137392m,
                            PalletId = 1,
                            Weight = 10.045168745957482m,
                            Width = 111.13323094897603181035961057m
                        },
                        new
                        {
                            Id = 19,
                            DateOfProdaction = new DateOnly(2022, 3, 24),
                            Depth = 24.566374916478879672028459518m,
                            Height = 43.05686336001452992710835255m,
                            PalletId = 8,
                            Weight = 6.893843267323816m,
                            Width = 11.361644524892494878737266552m
                        },
                        new
                        {
                            Id = 20,
                            Depth = 1.5436513544844162097627261562m,
                            ExpiryDate = new DateOnly(2020, 12, 6),
                            Height = 18.91958213595250373501229634m,
                            PalletId = 3,
                            Weight = 26.157677984690596m,
                            Width = 16.816124180059098589643520542m
                        },
                        new
                        {
                            Id = 21,
                            DateOfProdaction = new DateOnly(2020, 11, 4),
                            Depth = 161.73059332708210890875210287m,
                            Height = 114.66268992363952752709981710m,
                            PalletId = 3,
                            Weight = 23.841375654154938m,
                            Width = 20.967048914930666733065653893m
                        },
                        new
                        {
                            Id = 22,
                            Depth = 7.1538215661485424642940366672m,
                            ExpiryDate = new DateOnly(2022, 8, 6),
                            Height = 5.5573263537640587453647936925m,
                            PalletId = 3,
                            Weight = 6.855892459871108m,
                            Width = 21.365151622063038671664449423m
                        },
                        new
                        {
                            Id = 23,
                            DateOfProdaction = new DateOnly(2021, 11, 13),
                            Depth = 29.965402724015192490592555617m,
                            Height = 30.426163528871103500721981376m,
                            PalletId = 9,
                            Weight = 14.215820657520516m,
                            Width = 112.76504568672192246649032079m
                        },
                        new
                        {
                            Id = 24,
                            Depth = 289.96862619761157926620301394m,
                            ExpiryDate = new DateOnly(2021, 6, 11),
                            Height = 127.38521020365825431898157106m,
                            PalletId = 6,
                            Weight = 28.161589032096756m,
                            Width = 60.588635326971590680567711232m
                        },
                        new
                        {
                            Id = 25,
                            DateOfProdaction = new DateOnly(2021, 12, 3),
                            Depth = 169.74847073497901718331378344m,
                            Height = 110.03420658586361443014899053m,
                            PalletId = 7,
                            Weight = 27.979421601696364m,
                            Width = 264.76840981898689512820542845m
                        },
                        new
                        {
                            Id = 26,
                            Depth = 26.730643114211792298567610150m,
                            ExpiryDate = new DateOnly(2021, 7, 29),
                            Height = 12.572308836790841897528505665m,
                            PalletId = 8,
                            Weight = 25.665916642564139m,
                            Width = 163.25851459735708848778285897m
                        },
                        new
                        {
                            Id = 27,
                            DateOfProdaction = new DateOnly(2021, 1, 13),
                            Depth = 193.40635643225875787517556485m,
                            Height = 244.59644415736111705090033593m,
                            PalletId = 5,
                            Weight = 9.075887608693165m,
                            Width = 44.607673880029506659923999571m
                        },
                        new
                        {
                            Id = 28,
                            Depth = 119.25207002881773645251760815m,
                            ExpiryDate = new DateOnly(2022, 7, 8),
                            Height = 97.83244748230851080116006536m,
                            PalletId = 6,
                            Weight = 6.65644253749815m,
                            Width = 88.24093333976793518069197720m
                        },
                        new
                        {
                            Id = 29,
                            DateOfProdaction = new DateOnly(2021, 5, 27),
                            Depth = 13.446723537131670525114096107m,
                            Height = 140.49208251327424981062177896m,
                            PalletId = 1,
                            Weight = 13.958143528004905m,
                            Width = 232.66951869529896467812139351m
                        },
                        new
                        {
                            Id = 30,
                            Depth = 43.848583813427710957072185331m,
                            ExpiryDate = new DateOnly(2020, 12, 29),
                            Height = 151.16864019185292784127291880m,
                            PalletId = 8,
                            Weight = 2.1851721255178174m,
                            Width = 134.05548565315695027543435898m
                        },
                        new
                        {
                            Id = 31,
                            DateOfProdaction = new DateOnly(2021, 5, 13),
                            Depth = 90.85463455474892904293629656m,
                            Height = 260.51715239974315522998490329m,
                            PalletId = 5,
                            Weight = 19.893801102802337m,
                            Width = 46.305459834585728849414110947m
                        },
                        new
                        {
                            Id = 32,
                            Depth = 208.94569317052997105575326401m,
                            ExpiryDate = new DateOnly(2021, 1, 4),
                            Height = 125.32704626622279913472789661m,
                            PalletId = 6,
                            Weight = 14.418810328813497m,
                            Width = 169.23480201072854902798652177m
                        },
                        new
                        {
                            Id = 33,
                            DateOfProdaction = new DateOnly(2022, 8, 4),
                            Depth = 90.44463093613184449073255050m,
                            Height = 44.032928791813275122066217464m,
                            PalletId = 5,
                            Weight = 11.494678263263535m,
                            Width = 62.358425959659804137971237878m
                        },
                        new
                        {
                            Id = 34,
                            Depth = 48.753715327655332411844304543m,
                            ExpiryDate = new DateOnly(2021, 10, 31),
                            Height = 24.17726155328246311257840175m,
                            PalletId = 8,
                            Weight = 4.892111173722962m,
                            Width = 2.5222303003101516532206877665m
                        },
                        new
                        {
                            Id = 35,
                            DateOfProdaction = new DateOnly(2021, 3, 21),
                            Depth = 135.14018434635142990305630425m,
                            Height = 23.4938637148781946396826774m,
                            PalletId = 7,
                            Weight = 25.932151881346331m,
                            Width = 76.074458159393482722809223006m
                        },
                        new
                        {
                            Id = 36,
                            Depth = 12.352445648589465506075571670m,
                            ExpiryDate = new DateOnly(2022, 1, 21),
                            Height = 56.024813022528639381353678672m,
                            PalletId = 4,
                            Weight = 18.775244904097966m,
                            Width = 259.08557216950013468041728287m
                        },
                        new
                        {
                            Id = 37,
                            DateOfProdaction = new DateOnly(2022, 2, 5),
                            Depth = 223.29023491711753737214795238m,
                            Height = 43.470268530996060361999261045m,
                            PalletId = 3,
                            Weight = 22.908435399061954m,
                            Width = 28.726648761040661123272550357m
                        },
                        new
                        {
                            Id = 38,
                            Depth = 55.013072691565576641576213748m,
                            ExpiryDate = new DateOnly(2021, 4, 22),
                            Height = 229.42474071808483195724643484m,
                            PalletId = 6,
                            Weight = 13.411555913346306m,
                            Width = 119.45498082513515740276742828m
                        },
                        new
                        {
                            Id = 39,
                            DateOfProdaction = new DateOnly(2021, 1, 17),
                            Depth = 50.67998192115818505181597465m,
                            Height = 22.830429523598109896164607675m,
                            PalletId = 2,
                            Weight = 3.8978384613630454m,
                            Width = 23.143994288242320563672840645m
                        },
                        new
                        {
                            Id = 40,
                            Depth = 156.98106589121036070900030509m,
                            ExpiryDate = new DateOnly(2022, 4, 16),
                            Height = 16.897777167942630395921617858m,
                            PalletId = 7,
                            Weight = 23.34544028804414m,
                            Width = 64.47919260943902487847599092m
                        },
                        new
                        {
                            Id = 41,
                            DateOfProdaction = new DateOnly(2022, 8, 15),
                            Depth = 31.185263340156429990945553282m,
                            Height = 268.46830398729933799449363986m,
                            PalletId = 1,
                            Weight = 18.73809161328975m,
                            Width = 51.245197600899037796888017294m
                        },
                        new
                        {
                            Id = 42,
                            Depth = 213.54106226858046771911046402m,
                            ExpiryDate = new DateOnly(2021, 4, 14),
                            Height = 26.640322190991475663256955970m,
                            PalletId = 6,
                            Weight = 23.599992582151764m,
                            Width = 109.24247027166291223534689338m
                        },
                        new
                        {
                            Id = 43,
                            DateOfProdaction = new DateOnly(2022, 6, 20),
                            Depth = 39.168790201135385964458688926m,
                            Height = 67.59560839210949809407993165m,
                            PalletId = 8,
                            Weight = 24.686736322474316m,
                            Width = 82.79583579269432374998928487m
                        },
                        new
                        {
                            Id = 44,
                            Depth = 28.549893476374353735313733296m,
                            ExpiryDate = new DateOnly(2021, 11, 20),
                            Height = 157.58286894773496305150875714m,
                            PalletId = 1,
                            Weight = 14.06557689263462m,
                            Width = 142.22912437506917133021681847m
                        },
                        new
                        {
                            Id = 45,
                            DateOfProdaction = new DateOnly(2021, 3, 27),
                            Depth = 48.878131873316599574347650022m,
                            Height = 118.44482443163246629648202515m,
                            PalletId = 6,
                            Weight = 4.977519122224331m,
                            Width = 52.157860066589965947657768944m
                        },
                        new
                        {
                            Id = 46,
                            Depth = 113.50902434175615104564310322m,
                            ExpiryDate = new DateOnly(2020, 12, 13),
                            Height = 87.85336312892119131684424913m,
                            PalletId = 6,
                            Weight = 9.488955941349931m,
                            Width = 113.60447183074877849619975547m
                        },
                        new
                        {
                            Id = 47,
                            DateOfProdaction = new DateOnly(2021, 5, 13),
                            Depth = 85.06780831902959667542265522m,
                            Height = 39.487483871449684738793418831m,
                            PalletId = 3,
                            Weight = 8.664379836802402m,
                            Width = 4.3496460799057600308355509036m
                        },
                        new
                        {
                            Id = 48,
                            Depth = 37.011653901030223213853934967m,
                            ExpiryDate = new DateOnly(2022, 6, 21),
                            Height = 10.500623852540648567522429845m,
                            PalletId = 1,
                            Weight = 5.806415758553607m,
                            Width = 213.03117000664133176001764508m
                        },
                        new
                        {
                            Id = 49,
                            DateOfProdaction = new DateOnly(2021, 10, 7),
                            Depth = 31.875000264269103695689479308m,
                            Height = 179.48462710280102799157943988m,
                            PalletId = 1,
                            Weight = 17.765025219663586m,
                            Width = 151.27973814656838800453348365m
                        },
                        new
                        {
                            Id = 50,
                            Depth = 187.07877100049879339609447442m,
                            ExpiryDate = new DateOnly(2021, 9, 20),
                            Height = 47.042950404496615757364775451m,
                            PalletId = 3,
                            Weight = 17.953974889035302m,
                            Width = 14.396175722965636932825545656m
                        });
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Depth")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Height")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Width")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Depth = 41.3903981343342m,
                            Height = 243.653289777199m,
                            Width = 293.106845025685m
                        },
                        new
                        {
                            Id = 2,
                            Depth = 127.269367882135m,
                            Height = 95.7605498282308m,
                            Width = 82.6080191495418m
                        },
                        new
                        {
                            Id = 3,
                            Depth = 256.990592825701m,
                            Height = 35.7287990407294m,
                            Width = 124.118906755619m
                        },
                        new
                        {
                            Id = 4,
                            Depth = 12.5064807645807m,
                            Height = 274.892702639978m,
                            Width = 129.927474306476m
                        },
                        new
                        {
                            Id = 5,
                            Depth = 215.005327535618m,
                            Height = 75.1859077981136m,
                            Width = 291.217972037246m
                        },
                        new
                        {
                            Id = 6,
                            Depth = 299.819667553273m,
                            Height = 207.248462758802m,
                            Width = 275.538921875196m
                        },
                        new
                        {
                            Id = 7,
                            Depth = 211.271487309242m,
                            Height = 297.977224508646m,
                            Width = 169.07045211343m
                        },
                        new
                        {
                            Id = 8,
                            Depth = 56.5986732727583m,
                            Height = 197.078530148666m,
                            Width = 165.52234744295m
                        },
                        new
                        {
                            Id = 9,
                            Depth = 220.973419128597m,
                            Height = 212.531131978806m,
                            Width = 175.209174463318m
                        });
                });

            modelBuilder.Entity("Box", b =>
                {
                    b.HasOne("Pallet", "Pallet")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
